Repository Dashticz/dashticz, pull requests merged in 2019-08, with the labels that each got.

#25 Some small additions to Public Transport
  docs/blocks/specials/publictransport.rst
Labels: documentation

#29 Update weather_owm.js
  js/weather_owm.js
Labels: enhancement

#30 Issue: Documentation beta 2.5.1 #10
  docs/blocks/buttons.rst
  docs/blocks/domoticzblocks.rst
  docs/dashticzconfiguration.rst
Labels: documentation

#34 Added section and item to Styling via custom.css
  docs/customcss/customcss.rst
Labels: documentation

#37 CSS comments
  docs/customcss/customcss.rst
Labels: documentation

#38 [enh] To chartjs
  .gitignore
  css/creative.css
  custom/custom.js
  docs/blocks/blocks.rst
  docs/blocks/domoticzblocks.rst
  docs/blocks/graphs.rst
  docs/blocks/img/climate.jpg
  docs/blocks/img/climate_te_hu.jpg
  docs/blocks/img/p1.jpg
  docs/blocks/img/p1_custom.jpg
  docs/blocks/img/p1_legend.jpg
  docs/blocks/img/p1_legend_2.jpg
  docs/blocks/img/solar_1_default.jpg
  docs/blocks/img/solar_custom_legend.jpg
  docs/blocks/img/solar_default.jpg
  docs/blocks/img/solar_legend.jpg
  docs/blocks/img/solar_yellow_bar.jpg
  docs/blocks/js/CONFIG.chart.js
  docs/blocks/specials/weather.rst
  docs/customcss/customcss.rst
  docs/releasenotes.rst
  index.html
  js/blocks.js
  js/graphs.js
  js/weather_owm.js
  vendor/chart/Chart.bundle.min.js
Labels: enhancement

#39 [fix] width for chart
  js/graphs.js
Labels: bug

#42 [fix] graph height, tooltips, refresh rate
  js/graphs.js
Labels: enhancement
